name: CI
on:
  push:
    branches:
    - '*'
  schedule:
  - cron: 0 14 * * *
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Make missing versions
      run: ./build-all.sh
