name: CI
on:
  push:
    branches:
    - '*'
  schedule:
  - cron: 0 14 * * *
jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Docker registry login
      run: ./login.sh
      env:
        INPUT_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        INPUT_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Make missing versions
      run: ./build-all.sh
